apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
  labels:
    app: calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      name: calculator
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: ghcr.io/c-kuklinski/calculator

        imagePullPolicy: Always
        ports:
          - name: calculator
            containerPort: 8080
        livenessProbe:
          httpGet:
            port: calculator
            path: /actuator/health/liveness
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            port: calculator
            path: /actuator/health/readiness
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: calculator
  labels:
    app: calculator
spec:
  selector:
    app: calculator
  ports:
  - name: calculator
    nodePort: 30000
    port: 8080
    targetPort: calculator
  type: LoadBalancer
